name: Deploy to Cloud Run

env:
  SERVICE_NAME: datapath-17-agent-2026
  PROJECT_ID: datapath-17-agent-2026
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/datapath-17-agent-2026/repositorio-backend-langgraph-multiagente/imagen-backend-langchain-inmobiliaria

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Write Google service account credentials
        run: |
          mkdir -p application/credentials
          printf '%s' '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > application/credentials/service-account.json

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile.prod .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account=deploy-datapath-agente-inmobil@datapath-17-agent-2026.iam.gserviceaccount.com \
            --set-secrets="AGENT_TIMEZONE=AGENT_TIMEZONE:latest,CHATWOOT_ACCOUNT_ID=CHATWOOT_ACCOUNT_ID:latest,CHATWOOT_API_ACCESS_TOKEN=CHATWOOT_API_ACCESS_TOKEN:latest,CHATWOOT_BASE_URL=CHATWOOT_BASE_URL:latest,CHATWOOT_BOT_LABEL=CHATWOOT_BOT_LABEL:latest,DB_HOST=DB_HOST:latest,DB_NAME=DB_NAME:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_PORT=DB_PORT:latest,DB_USER=DB_USER:latest,GOOGLE_SHEETS_HEADER_ROW=GOOGLE_SHEETS_HEADER_ROW:latest,GOOGLE_SHEETS_WORKSHEET=GOOGLE_SHEETS_WORKSHEET:latest,GOOGLE_SHEET_ID=GOOGLE_SHEET_ID:latest,GOOGLE_SHEET_ID_PROPIEDADES=GOOGLE_SHEET_ID_PROPIEDADES:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,QDRANT_API_KEY=QDRANT_API_KEY:latest,QDRANT_COLLECTION=QDRANT_COLLECTION:latest,QDRANT_URL=QDRANT_URL:latest,TAVILY_API_KEY=TAVILY_API_KEY:latest"
            